## Deep Learning - Artificial Neural Network

Data Preprocessing
Building ANN
Training ANN
Prediction

In [95]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [96]:
tf.__version__

'2.13.0'

## Data Preprocessing

### Feature scaling is an essential step in all deep learning models.

In [97]:
data=pd.read_csv('Churn_Modelling.csv')
data.head(3)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1

##### Description

In [98]:
data.shape

(10000, 14)

Tenure- the number of years they've been in the Bank.
NumOfProducts- credit card, check book.
Exited- Dependent var- The customer stayed in bank-1 or left the bank-0

### Checking missing values

In [99]:
data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [100]:
for i, e in enumerate(data):
    print(i,e)

0 RowNumber
1 CustomerId
2 Surname
3 CreditScore
4 Geography
5 Gender
6 Age
7 Tenure
8 Balance
9 NumOfProducts
10 HasCrCard
11 IsActiveMember
12 EstimatedSalary
13 Exited


### Assigning x and y

In [101]:
x=data.iloc[:,3:13].values
y=data.iloc[:,-1:].values

### Encoding

##### Gender and Geography

##### Label encoding for Gender feature

In [102]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [103]:
x[:,2]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

In [104]:
k=data.iloc[:,3:13]
for i,j in enumerate(k):
    print(i,j)

0 CreditScore
1 Geography
2 Gender
3 Age
4 Tenure
5 Balance
6 NumOfProducts
7 HasCrCard
8 IsActiveMember
9 EstimatedSalary


##### OneHotEncoding for Geography feature

In [105]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])], remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [106]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting

In [107]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

### Feature Scaling

In [108]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

## Building ANN

### 1- Initialize ANN

In [109]:
ann=tf.keras.models.Sequential()

### 2- Adding the input layer and the first hidden layer

In [110]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### 3- Adding the second hidden layer

In [111]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### 4- Adding the output layer

In [112]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

## Training the ANN

### 1- Compiling ANN with optimizer- Cost function

optimizer- 'adam'- stochastic gradient descent- minimize cost function(Error) by updating the weights.
loss- difference of predicted and actual o/p. For multi class o/p: 'category_crossentropy'
metrics- accuracy purpose. 

In [113]:
ann.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])

### 2- Train ANN on training dataset

batch_size= the batch of rows you want to run.
An epoch in a neural network is the training of the neural network with all the training data for one cycle.

In [114]:
ann.fit(x_train,y_train,batch_size=32, epochs=100)

Epoch 1/100
235/235 [==============================] - 1s 2ms/step - loss: 0.6137 - accuracy: 0.7432
Epoch 2/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4814 - accuracy: 0.7963
Epoch 3/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4428 - accuracy: 0.7963
Epoch 4/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4263 - accuracy: 0.7967
Epoch 5/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4112 - accuracy: 0.8047
Epoch 6/100
235/235 [==============================] - 0s 2ms/step - loss: 0.3960 - accuracy: 0.8136
Epoch 7/100
235/235 [==============================] - 0s 2ms/step - loss: 0.3840 - accuracy: 0.8180
Epoch 8/100
235/235 [==============================] - 0s 2ms/step - loss: 0.3758 - accuracy: 0.8203
Epoch 9/100
235/235 [==============================] - 0s 2ms/step - loss: 0.3710 - accuracy: 0.8208
Epoch 10/100
235/235 [==============================] - 0s 2ms/step - loss: 0.3675 - accura

## Prediction and Evaluation

In [115]:
data['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [116]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])))

1/1 [==============================] - 0s 160ms/step
[[0.08616529]]


In [117]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [127]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) < 0.001)

1/1 [==============================] - 0s 66ms/step
[[False]]


### Prediction - Test set

In [128]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

79/79 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Confusion Matrix

In [129]:
from sklearn.metrics import confusion_matrix, accuracy_score
matrix=confusion_matrix(y_test,y_pred)
accuracy=accuracy_score(y_test,y_pred)

In [130]:
matrix

array([[1887,  104],
       [ 239,  270]], dtype=int64)

In [131]:
accuracy

0.8628